resource "aws_db_instance" "tfer--likeminds-staging-caravan-rds" {
  allocated_storage                     = "435"
  auto_minor_version_upgrade            = "true"
  availability_zone                     = "ap-south-1a"
  backup_retention_period               = "7"
  backup_target                         = "region"
  backup_window                         = "21:02-21:32"
  ca_cert_identifier                    = "rds-ca-2019"
  copy_tags_to_snapshot                 = "true"
  customer_owned_ip_enabled             = "false"
  db_subnet_group_name                  = "${aws_db_subnet_group.tfer--likeminds-staging-rds-subnet-group.name}"
  dedicated_log_volume                  = "false"
  deletion_protection                   = "true"
  enabled_cloudwatch_logs_exports       = ["postgresql", "upgrade"]
  engine                                = "postgres"
  engine_version                        = "12.17"
  iam_database_authentication_enabled   = "false"
  identifier                            = "likeminds-staging-caravan-rds"
  instance_class                        = "db.t4g.medium"
  iops                                  = "0"
  kms_key_id                            = "arn:aws:kms:ap-south-1:081371230266:key/739c7b29-edbe-4221-8094-1d239d83ce22"
  license_model                         = "postgresql-license"
  maintenance_window                    = "sun:10:36-sun:11:06"
  max_allocated_storage                 = "1000"
  monitoring_interval                   = "60"
  monitoring_role_arn                   = "arn:aws:iam::081371230266:role/rds-monitoring-role"
  multi_az                              = "false"
  network_type                          = "IPV4"
  option_group_name                     = "default:postgres-12"
  parameter_group_name                  = "${aws_db_parameter_group.tfer--likeminds-staging-rds-parameter-group-12.name}"
  performance_insights_enabled          = "false"
  performance_insights_kms_key_id       = "arn:aws:kms:ap-south-1:081371230266:key/739c7b29-edbe-4221-8094-1d239d83ce22"
  performance_insights_retention_period = "0"
  port                                  = "5432"
  publicly_accessible                   = "false"
  storage_encrypted                     = "true"
  storage_throughput                    = "0"
  storage_type                          = "gp2"

  tags = {
    CreatedBy = "Rapyder"
    Env       = "staging"
    Name      = "likeminds-staging-caravan-rds"
  }

  tags_all = {
    CreatedBy = "Rapyder"
    Env       = "staging"
    Name      = "likeminds-staging-caravan-rds"
  }

  username               = "postgres"
  vpc_security_group_ids = ["sg-03a1d8902ebbd355d"]
}

resource "aws_db_instance" "tfer--likeminds-staging-caravan-reader" {
  allocated_storage                     = "200"
  auto_minor_version_upgrade            = "true"
  availability_zone                     = "ap-south-1b"
  backup_retention_period               = "0"
  backup_target                         = "region"
  backup_window                         = "21:02-21:32"
  ca_cert_identifier                    = "rds-ca-2019"
  copy_tags_to_snapshot                 = "false"
  customer_owned_ip_enabled             = "false"
  db_subnet_group_name                  = "${aws_db_subnet_group.tfer--likeminds-staging-rds-subnet-group.name}"
  dedicated_log_volume                  = "false"
  deletion_protection                   = "true"
  enabled_cloudwatch_logs_exports       = ["postgresql", "upgrade"]
  iam_database_authentication_enabled   = "false"
  identifier                            = "likeminds-staging-caravan-reader"
  instance_class                        = "db.t4g.small"
  iops                                  = "0"
  kms_key_id                            = "arn:aws:kms:ap-south-1:081371230266:key/739c7b29-edbe-4221-8094-1d239d83ce22"
  license_model                         = "postgresql-license"
  maintenance_window                    = "sun:10:36-sun:11:06"
  max_allocated_storage                 = "1000"
  monitoring_interval                   = "0"
  multi_az                              = "false"
  network_type                          = "IPV4"
  option_group_name                     = "default:postgres-12-db-jnudssz55x6kkvg7bnwfrwbue4-upgrade"
  parameter_group_name                  = "default.postgres12-db-jnudssz55x6kkvg7bnwfrwbue4-upgrade"
  performance_insights_enabled          = "false"
  performance_insights_kms_key_id       = "arn:aws:kms:ap-south-1:081371230266:key/739c7b29-edbe-4221-8094-1d239d83ce22"
  performance_insights_retention_period = "0"
  port                                  = "5432"
  publicly_accessible                   = "false"
  replicate_source_db                   = "likeminds-staging-caravan-rds"
  storage_encrypted                     = "true"
  storage_throughput                    = "0"
  storage_type                          = "gp2"
  vpc_security_group_ids                = ["sg-03a1d8902ebbd355d"]
}

resource "aws_db_instance" "tfer--likeminds-staging-growth-hacks-rds" {
  allocated_storage                     = "20"
  auto_minor_version_upgrade            = "true"
  availability_zone                     = "ap-south-1b"
  backup_retention_period               = "7"
  backup_target                         = "region"
  backup_window                         = "22:04-22:34"
  ca_cert_identifier                    = "rds-ca-2019"
  copy_tags_to_snapshot                 = "true"
  customer_owned_ip_enabled             = "false"
  db_subnet_group_name                  = "${aws_db_subnet_group.tfer--likeminds-staging-rds-subnet-group.name}"
  dedicated_log_volume                  = "false"
  deletion_protection                   = "true"
  engine                                = "postgres"
  engine_version                        = "14.10"
  iam_database_authentication_enabled   = "false"
  identifier                            = "likeminds-staging-growth-hacks-rds"
  instance_class                        = "db.t4g.micro"
  iops                                  = "3000"
  kms_key_id                            = "arn:aws:kms:ap-south-1:081371230266:key/739c7b29-edbe-4221-8094-1d239d83ce22"
  license_model                         = "postgresql-license"
  maintenance_window                    = "sat:13:30-sat:14:00"
  max_allocated_storage                 = "1000"
  monitoring_interval                   = "60"
  monitoring_role_arn                   = "arn:aws:iam::081371230266:role/rds-monitoring-role"
  multi_az                              = "false"
  network_type                          = "IPV4"
  option_group_name                     = "default:postgres-14"
  parameter_group_name                  = "default.postgres14"
  performance_insights_enabled          = "true"
  performance_insights_kms_key_id       = "arn:aws:kms:ap-south-1:081371230266:key/739c7b29-edbe-4221-8094-1d239d83ce22"
  performance_insights_retention_period = "7"
  port                                  = "5432"
  publicly_accessible                   = "false"
  storage_encrypted                     = "true"
  storage_throughput                    = "125"
  storage_type                          = "gp3"
  username                              = "postgres"
  vpc_security_group_ids                = ["sg-09b9f78c47c841089"]
}

resource "aws_db_instance" "tfer--likeminds-staging-skulk-rds" {
  allocated_storage                     = "100"
  auto_minor_version_upgrade            = "true"
  availability_zone                     = "ap-south-1a"
  backup_retention_period               = "7"
  backup_target                         = "region"
  backup_window                         = "18:25-18:55"
  ca_cert_identifier                    = "rds-ca-2019"
  copy_tags_to_snapshot                 = "true"
  customer_owned_ip_enabled             = "false"
  db_subnet_group_name                  = "${aws_db_subnet_group.tfer--likeminds-staging-rds-subnet-group.name}"
  dedicated_log_volume                  = "false"
  deletion_protection                   = "true"
  enabled_cloudwatch_logs_exports       = ["postgresql", "upgrade"]
  engine                                = "postgres"
  engine_version                        = "12.17"
  iam_database_authentication_enabled   = "false"
  identifier                            = "likeminds-staging-skulk-rds"
  instance_class                        = "db.t4g.micro"
  iops                                  = "0"
  kms_key_id                            = "arn:aws:kms:ap-south-1:081371230266:key/739c7b29-edbe-4221-8094-1d239d83ce22"
  license_model                         = "postgresql-license"
  maintenance_window                    = "sat:09:58-sat:10:28"
  max_allocated_storage                 = "1000"
  monitoring_interval                   = "60"
  monitoring_role_arn                   = "arn:aws:iam::081371230266:role/rds-monitoring-role"
  multi_az                              = "false"
  network_type                          = "IPV4"
  option_group_name                     = "default:postgres-12"
  parameter_group_name                  = "${aws_db_parameter_group.tfer--likeminds-staging-rds-parameter-group-12.name}"
  performance_insights_enabled          = "false"
  performance_insights_kms_key_id       = "arn:aws:kms:ap-south-1:081371230266:key/739c7b29-edbe-4221-8094-1d239d83ce22"
  performance_insights_retention_period = "0"
  port                                  = "5432"
  publicly_accessible                   = "false"
  storage_encrypted                     = "true"
  storage_throughput                    = "0"
  storage_type                          = "gp2"

  tags = {
    CreatedBy       = "Rapyder"
    Env             = "staging"
    Name            = "likeminds-staging-skulk-rds"
    auto-start-stop = "Yes"
  }

  tags_all = {
    CreatedBy       = "Rapyder"
    Env             = "staging"
    Name            = "likeminds-staging-skulk-rds"
    auto-start-stop = "Yes"
  }

  username               = "postgres"
  vpc_security_group_ids = ["sg-0f055310794c97634"]
}
